-- 🧹 LEDGR ERP: ENHANCED SEED CLEANUP SCRIPT
-- --------------------------------------------------
-- This script removes all data generated by Seeding Phase 1 & 2.
-- It targets records with 'is_seed = TRUE' or 'seeder_' / 'seed_' prefixes.

BEGIN;

-- 1. DELETE TRANSACTIONAL DATA (Order: Children first)
DELETE FROM public.invoices WHERE is_seed = TRUE OR id LIKE 'seed_inv_%';
DELETE FROM public.client_payments WHERE id LIKE 'seed_cp_%';
DELETE FROM public.sales WHERE is_seed = TRUE OR id LIKE 'seed_sale_%' OR id LIKE 'seed_trend_%';
DELETE FROM public.payroll WHERE is_seed = TRUE OR id LIKE 'seed_pay_%';
DELETE FROM public.expenses WHERE is_seed = TRUE OR id LIKE 'seed_exp_%';
DELETE FROM public.movement_log WHERE is_seed = TRUE OR id LIKE 'seed_mov_%';
DELETE FROM public.purchases WHERE id LIKE 'seed_pur_%';

-- 2. DELETE LOGISTICS DATA
DELETE FROM public.routes WHERE id LIKE 'seeder_route_%';
DELETE FROM public.vehicles WHERE id LIKE 'seeder_veh_%';

-- 3. DELETE MASTER DATA
DELETE FROM public.employees WHERE is_seed = TRUE OR id LIKE 'seeder_emp_%';
DELETE FROM public.clients WHERE is_seed = TRUE OR id LIKE 'seeder_cli_%';
DELETE FROM public.products WHERE is_seed = TRUE OR id LIKE 'seeder_prod_%';

-- 4. DELETE DASHBOARD SPECIALS
DELETE FROM public.day_book WHERE id = 'seed_db_today';

COMMIT;
