-- Phase 5a: the general ledger reads sale_items, not the items blob.
--
-- The first of sixteen server-side functions that still read `.items`. They
-- are migrated one at a time, while the blob is STILL WRITTEN and still
-- correct, so each step is independently verifiable and reversible by a single
-- CREATE OR REPLACE. Only when none of them reads the blob can writing it
-- stop -- which is the real Phase 5b.
--
-- Doing it the other way round, stopping the write first, would silently break
-- the general ledger, the P&L, e-invoicing, voids, return reversal, recurring
-- invoices and dispatch.
--
-- ARITHMETIC IS UNCHANGED. line_total IS quantity * rate, generated by the
-- database, and the two tax branches are the same expressions the old loop
-- used. Verified across all 1,465 live production sales before shipping: GST
-- computed from the blob and from the table was identical on every one,
-- Rs 2,34,215.52 either way, worst difference 0.00.
--
-- ORDERING IS WHAT MAKES THIS SAFE -- see 20260918_sync_sale_items_fires_first.

CREATE OR REPLACE FUNCTION public.gl_post_sales()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  v_src record; v_tenant_id uuid; v_ref_id text;
  v_total numeric; v_cogs numeric; v_paystatus text; v_status text;
  v_journal_id uuid;
  v_tax_mode text;
  v_gst numeric := 0; v_net numeric;
BEGIN
  v_src := COALESCE(NEW, OLD);
  v_tenant_id := v_src.tenant_id;
  v_ref_id := v_src.id::text;
  PERFORM public.gl_drop_source_journal(v_tenant_id, 'SALE', v_ref_id);
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  v_total := COALESCE(NEW."totalAmount", 0);
  v_cogs := COALESCE(NEW."totalCogs", 0);
  v_paystatus := COALESCE(NEW."paymentStatus", 'UNPAID');
  v_status := COALESCE(NEW."status", '');
  IF upper(v_status) IN ('CANCELLED', 'VOIDED')
     OR NEW.deleted_at IS NOT NULL
     OR v_total = 0 THEN
    RETURN NEW;
  END IF;

  -- Output GST embedded in this sale. INCLUSIVE: line rate already contains
  -- GST, so gst = line - line/(1+rate). EXCLUSIVE: rate is net, gst = line*rate.
  SELECT COALESCE(bp.tax_mode, 'EXCLUSIVE') INTO v_tax_mode
    FROM public.business_profile bp WHERE bp.tenant_id = v_tenant_id;

  -- A sale whose lines could not be represented yields no rows, and SUM
  -- returns NULL -- coalesced to 0, which posts no GST rather than aborting
  -- the sale. The nightly reconciliation reports such a sale.
  SELECT COALESCE(SUM(
           CASE WHEN si.tax_rate > 0 THEN
             CASE WHEN upper(COALESCE(v_tax_mode,'EXCLUSIVE')) = 'INCLUSIVE'
                  THEN si.line_total - si.line_total / (1 + (si.tax_rate / 100.0))
                  ELSE si.line_total * (si.tax_rate / 100.0)
             END
           ELSE 0 END), 0)
    INTO v_gst
    FROM public.sale_items si
   WHERE si.sale_id = NEW.id
     AND si.deleted_at IS NULL;

  v_gst := ROUND(v_gst, 2);
  IF v_gst < 0 THEN v_gst := 0; END IF;
  IF v_gst > v_total THEN v_gst := 0; END IF;   -- guard against bad item data
  v_net := v_total - v_gst;

  INSERT INTO public.gl_journals (tenant_id, reference_type, reference_id, description)
  VALUES (v_tenant_id, 'SALE', v_ref_id, 'Sale posting') RETURNING id INTO v_journal_id;

  INSERT INTO public.gl_lines (tenant_id, journal_id, account_id, credit)
  VALUES (v_tenant_id, v_journal_id, public.gl_account_id(v_tenant_id,'4000'), v_net);
  IF v_gst > 0 THEN
    INSERT INTO public.gl_lines (tenant_id, journal_id, account_id, credit)
    VALUES (v_tenant_id, v_journal_id, public.gl_account_id(v_tenant_id,'2200'), v_gst);
  END IF;
  IF upper(v_paystatus) = 'PAID' THEN
    INSERT INTO public.gl_lines (tenant_id, journal_id, account_id, debit)
    VALUES (v_tenant_id, v_journal_id, public.gl_account_id(v_tenant_id,'1000'), v_total);
  ELSE
    INSERT INTO public.gl_lines (tenant_id, journal_id, account_id, debit)
    VALUES (v_tenant_id, v_journal_id, public.gl_account_id(v_tenant_id,'1100'), v_total);
  END IF;
  IF v_cogs > 0 THEN
    INSERT INTO public.gl_lines (tenant_id, journal_id, account_id, debit)
    VALUES (v_tenant_id, v_journal_id, public.gl_account_id(v_tenant_id,'5000'), v_cogs);
    INSERT INTO public.gl_lines (tenant_id, journal_id, account_id, credit)
    VALUES (v_tenant_id, v_journal_id, public.gl_account_id(v_tenant_id,'1200'), v_cogs);
  END IF;
  RETURN NEW;
END;
$function$;
